import {
  Sparkles,
  SprayCan,
  Sofa,
  ShoppingBasket,
  Home,
  UtensilsCrossed,
  Laptop,
  Shirt,
  Footprints,
  Watch,
  Smartphone,
  Bike,
  Droplet,
  Dumbbell,
  Glasses,
  Tablet,
  Car,
  ShoppingBag,
  Gem,
  LayoutGrid,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  beauty: Sparkles,
  fragrances: SprayCan,
  furniture: Sofa,
  groceries: ShoppingBasket,
  'home-decoration': Home,
  'kitchen-accessories': UtensilsCrossed,
  laptops: Laptop,
  'mens-shirts': Shirt,
  'mens-shoes': Footprints,
  'mens-watches': Watch,
  'mobile-accessories': Smartphone,
  motorcycle: Bike,
  'skin-care': Droplet,
  smartphones: Smartphone,
  'sports-accessories': Dumbbell,
  sunglasses: Glasses,
  tablets: Tablet,
  tops: Shirt,
  vehicle: Car,
  'womens-bags': ShoppingBag,
  'womens-dresses': Shirt,
  'womens-jewellery': Gem,
  'womens-shoes': Footprints,
  'womens-watches': Watch,
};

export const DEFAULT_CATEGORY_ICON: LucideIcon = LayoutGrid;
